
development: &id1
  clients:
    default:
      database: ish_development
      hosts:
        - 127.0.0.1
development_cached: *id1
development_production: *id1

test:
  clients:
    default:
      database: ish_test
      hosts:
        - 127.0.0.1

production:
  clients:
    default:
      database: ish_development
      hosts:
        - 127.0.0.1